name: Check First Commit
description: An action to ensure a workflow runs only if this is the first commit on the default branch and not a fork or PR
branding:
  icon: 'check-square'
  color: 'blue'
outputs:
  first_commit:
    description: "Whether this is the first commit"
    value: ${{ steps.first-check.outputs.first_commit }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: first-check
      run: |
        echo "event_name=${{ github.event_name }}"
        echo "is_fork=${{ github.event.repository.fork }}"
        echo "head_ref=${{ github.head_ref }}"
        if [ "${{ github.event_name }}" != "push" ]; then
          echo "Not a push event — skipping."
          echo "first_commit=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        if [ "${{ github.event.repository.fork }}" = "true" ]; then
          echo "This is a fork — skipping."
          echo "first_commit=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        if [ "${{ github.head_ref }}" != "" ]; then
          echo "This is a PR — skipping."
          echo "first_commit=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        # Ensure we're in the default branch
        DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
        CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        echo "default_branch=$DEFAULT_BRANCH"
        echo "current_branch=$CURRENT_BRANCH"
        if [ "$CURRENT_BRANCH" != "$DEFAULT_BRANCH" ]; then
          echo "Not on default branch — skipping."
          echo "first_commit=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        # Check for exactly one commit in the repo
        COMMIT_COUNT=$(git rev-list --count HEAD)
        echo "commit_count=$COMMIT_COUNT"
        if [ "$COMMIT_COUNT" -eq 1 ]; then
          echo "This is the first/root commit."
          echo "first_commit=true" >> "$GITHUB_OUTPUT"
        else
          echo "Not the first commit."
          echo "first_commit=false" >> "$GITHUB_OUTPUT"
        fi
